"""add time col

Revision ID: d9b8c5f30d5e
Revises: 090a6cedddb7
Create Date: 2022-03-14 19:15:49.149942

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d9b8c5f30d5e"
down_revision = "090a6cedddb7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("data", sa.Column("time", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("data", "time")
    # ### end Alembic commands ###
